// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2I66d7JhNhCsU0ZcTlf6ryEeoMa55TeA',
    appId: '1:770810950615:android:8569708c328c63185e9192',
    messagingSenderId: '770810950615',
    projectId: 'venwall-a5827',
    storageBucket: 'venwall-a5827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHCESTMnex1y4P5MwezVH08W-makpYXI',
    appId: '1:770810950615:ios:8d0cb38516fc5ebc5e9192',
    messagingSenderId: '770810950615',
    projectId: 'venwall-a5827',
    storageBucket: 'venwall-a5827.firebasestorage.app',
    iosBundleId: 'com.app.venwall',
    iosClientId: '770810950615-d5jb4u638ldvjq95n2i42vaivf1ujc6v.apps.googleusercontent.com',
    //
  );


  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDjIZm7xgZ321cg7pPHSVR_WVZJQrZL_Ek",
      authDomain: "calculators-f98c1.firebaseapp.com",
      projectId: "calculators-f98c1",
      storageBucket: "calculators-f98c1.firebasestorage.app",
      messagingSenderId: "594013064633",
      appId: "1:594013064633:web:c86839bc775c7d6fe47a68",
      measurementId: "G-QVHHLB57M5"
  );

}
